export {assertIsArray} from './assertIsArray'
export {assertIsFrozen} from './assertIsFrozen'
export {assertIsFunction} from './assertIsFunction'
export {assertIsNumber} from './assertIsNumber'
export {assertIsObject} from './assertIsObject'
export {assertIsSealed} from './assertIsSealed'
export {assertIsString} from './assertIsString'
